version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/datman
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - restore_cache:
          key: tox-env-{{ .Branch }}-{{ checksum "setup.cfg" }}
      - run:
          command: |
            tox
      - codecov/upload:
          file: tests/results/junit*xml
          flags: unittests
      - save_cache:
          key: tox-env-{{ .Branch }}-{{ checksum "setup.cfg" }}
          paths: .tox
